services:
  app:
    env_file: .docker.env
    build:
      context: ./docker/
    working_dir: /var/www
    volumes:
      - ./:/var/www
    depends_on:
      - "queue"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      PHP_IDE_CONFIG: "serverName=aiobackoffice.app"
  queue:
    env_file: .docker.env
    restart: 'unless-stopped'
    build:
      context: ./docker/
    working_dir: /var/www
    volumes:
      - ./:/var/www
    command: "/bin/sh -c 'php artisan queue:work --delay=10 --memory=2048 --timeout=3600 --max-jobs=10'"
  scheduler:
    env_file: .docker.env
    restart: 'unless-stopped'
    build:
      context: ./docker/
    working_dir: /var/www
    volumes:
      - ./:/var/www
    command: "/bin/sh -c 'php artisan schedule:work'"
  nginx:
    image: nginx:stable
    working_dir: /var/www
    depends_on:
      - "app"
    ports:
      - "8777:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/dev.conf:/etc/nginx/conf.d/default.conf
